import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// AnuPpuccin — ported from Obsidian theme `anubisnekhet/AnuPpuccin` by anubisnekhet.
// Rank #4 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#1e1e2e",
      surface1: "#181825",
      surface2: "#c6d0f5",
      surface3: "#313244",
      surface4: "#313244",
      surfaceDiffEmpty: "#181825",
      surfaceSidebar: "#181825",
      surfaceSidebarHover: "#c6d0f5",
      foregroundMuted: "#8e95b3",
      foregroundExtraMuted: "#a1a8c9",
      scrollbarHandle: "#a1a8c9",
      border: "#313244",
      borderAccent: "#313244",
      accent: "#b4befe",
      accentBright: "#b4befe",
      accentForeground: "#1e1e2e",
      destructive: "#f38ba8",
});

const light = {
  surface0: "#eff1f5",
  surface1: "#e6e9ef",
  surface2: "#4c4f69",
  surface3: "#bcc0cc",
  surface4: "#bcc0cc",
  surfaceDiffEmpty: "#e6e9ef",
  surfaceSidebar: "#e6e9ef",
  surfaceSidebarHover: "#4c4f69",
  foreground: "#4c4f69",
  foregroundMuted: "#7c7f93",
  foregroundExtraMuted: "#6c6f85",
  scrollbarHandle: "#6c6f85",
  border: "#bcc0cc",
  borderAccent: "#bcc0cc",
  accent: "#7287fd",
  accentBright: "#7287fd",
  accentForeground: "#eff1f5",
  destructive: "#d20f39",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "anuppuccin",
  name: "AnuPpuccin",
  source: { repo: "anubisnekhet/AnuPpuccin", author: "anubisnekhet", rank: 4 },
  dark,
  light,
  terminalDark: {
    background: "#1e1e2e",
    foreground: "#1e1e2e",
    cursor: "#1e1e2e",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
    blue: "#87b0f9",
    magenta: "#b4befe",
    cyan: "#89dceb",
    white: "#1e1e2e",
    brightRed: "#f38ba8",
    brightGreen: "#a6e3a1",
    brightYellow: "#f9e2af",
    brightBlue: "#87b0f9",
    brightMagenta: "#f5c2e7",
    brightCyan: "#89dceb",
    brightWhite: "#1e1e2e",
  },
  terminalLight: {
    background: "#eff1f5",
    foreground: "#4c4f69",
    cursor: "#4c4f69",
    red: "#d20f39",
    green: "#40a02b",
    yellow: "#e49320",
    blue: "#2a6ef5",
    magenta: "#7287fd",
    cyan: "#04a5e5",
    white: "#4c4f69",
    brightRed: "#d20f39",
    brightGreen: "#40a02b",
    brightYellow: "#e49320",
    brightBlue: "#2a6ef5",
    brightMagenta: "#ec83d0",
    brightCyan: "#04a5e5",
    brightWhite: "#4c4f69",
  },
};
