import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Border — ported from Obsidian theme `akifyss/obsidian-border` by akifyss.
// Rank #19 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#000000",
      surface1: "#000000",
      surface2: "#1e1e1e",
      surface3: "#363636",
      surface4: "#363636",
      surfaceDiffEmpty: "#000000",
      surfaceSidebar: "#000000",
      surfaceSidebarHover: "#1e1e1e",
      foregroundMuted: "#999999",
      foregroundExtraMuted: "#666666",
      scrollbarHandle: "#666666",
      border: "#363636",
      borderAccent: "#363636",
      accent: "#707bc2",
      accentBright: "#818bc9",
      accentForeground: "#1e1e1e",
      destructive: "#ff7881",
});

const light = {
  surface0: "#ffffff",
  surface1: "#fafafa",
  surface2: "#e3e3e3",
  surface3: "#e0e0e0",
  surface4: "#e0e0e0",
  surfaceDiffEmpty: "#fafafa",
  surfaceSidebar: "#fafafa",
  surfaceSidebarHover: "#e3e3e3",
  foreground: "#1d1d20",
  foregroundMuted: "#707070",
  foregroundExtraMuted: "#ababab",
  scrollbarHandle: "#ababab",
  border: "#e0e0e0",
  borderAccent: "#e0e0e0",
  accent: "#4b63fb",
  accentBright: "#4459e2",
  accentForeground: "#ffffff",
  destructive: "#dd2c38",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "border",
  name: "Border",
  source: { repo: "akifyss/obsidian-border", author: "akifyss", rank: 19 },
  dark,
  light,
  terminalDark: {
    background: "#000000",
    foreground: "#d3d5de",
    cursor: "#d3d5de",
    red: "#ff7881",
    green: "#7cd37c",
    yellow: "#ffe88b",
    blue: "#89bdf4",
    magenta: "#cb9eff",
    cyan: "#86dfe2",
    white: "#d3d5de",
    brightRed: "#ff7881",
    brightGreen: "#7cd37c",
    brightYellow: "#ffe88b",
    brightBlue: "#89bdf4",
    brightMagenta: "#f2b6de",
    brightCyan: "#86dfe2",
    brightWhite: "#d3d5de",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#1d1d20",
    cursor: "#1d1d20",
    red: "#dd2c38",
    green: "#1da51d",
    yellow: "#c09c0c",
    blue: "#1775d9",
    magenta: "#8f47e1",
    cyan: "#16a6ab",
    white: "#1d1d20",
    brightRed: "#dd2c38",
    brightGreen: "#1da51d",
    brightYellow: "#c09c0c",
    brightBlue: "#1775d9",
    brightMagenta: "#dd1399",
    brightCyan: "#16a6ab",
    brightWhite: "#1d1d20",
  },
};
