import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Catppuccin — ported from Obsidian theme `catppuccin/obsidian` by catppuccin.
// Rank #16 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#1e1e2e",
      surface1: "#181825",
      surface2: "#181825",
      surface3: "#313244",
      surface4: "#313244",
      surfaceDiffEmpty: "#181825",
      surfaceSidebar: "#181825",
      surfaceSidebarHover: "#181825",
      foregroundMuted: "#a6adc8",
      foregroundExtraMuted: "#45475a",
      scrollbarHandle: "#45475a",
      border: "#313244",
      borderAccent: "#313244",
      accent: "#cba6f7",
      accentBright: "#cba6f7",
      accentForeground: "#181825",
      destructive: "#f38ba8",
});

const light = {
  surface0: "#eff1f5",
  surface1: "#e6e9ef",
  surface2: "#e6e9ef",
  surface3: "#ccd0da",
  surface4: "#ccd0da",
  surfaceDiffEmpty: "#e6e9ef",
  surfaceSidebar: "#e6e9ef",
  surfaceSidebarHover: "#e6e9ef",
  foreground: "#e6e9ef",
  foregroundMuted: "#6c6f85",
  foregroundExtraMuted: "#bcc0cc",
  scrollbarHandle: "#bcc0cc",
  border: "#ccd0da",
  borderAccent: "#ccd0da",
  accent: "#8839ef",
  accentBright: "#8839ef",
  accentForeground: "#e6e9ef",
  destructive: "#d20f39",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "catppuccin",
  name: "Catppuccin",
  source: { repo: "catppuccin/obsidian", author: "catppuccin", rank: 16 },
  dark,
  light,
  terminalDark: {
    background: "#1e1e2e",
    foreground: "#181825",
    cursor: "#181825",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
    blue: "#89b4fa",
    magenta: "#b4befe",
    cyan: "#89dceb",
    white: "#181825",
    brightRed: "#f38ba8",
    brightGreen: "#a6e3a1",
    brightYellow: "#f9e2af",
    brightBlue: "#89b4fa",
    brightMagenta: "#f5c2e7",
    brightCyan: "#89dceb",
    brightWhite: "#181825",
  },
  terminalLight: {
    background: "#eff1f5",
    foreground: "#e6e9ef",
    cursor: "#e6e9ef",
    red: "#d20f39",
    green: "#40a02b",
    yellow: "#df8e1d",
    blue: "#1e66f5",
    magenta: "#7287fd",
    cyan: "#04a5e5",
    white: "#e6e9ef",
    brightRed: "#d20f39",
    brightGreen: "#40a02b",
    brightYellow: "#df8e1d",
    brightBlue: "#1e66f5",
    brightMagenta: "#ea76cb",
    brightCyan: "#04a5e5",
    brightWhite: "#e6e9ef",
  },
};
