import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Cyber Glow — ported from Obsidian theme `thepharaohart/Obsidian-CyberGlow` by thepharaohart.
// Rank #51 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#000000",
      surface1: "#1e1e1e",
      surface2: "#1e1e1e",
      surface3: "#2e2e2e",
      surface4: "#2e2e2e",
      surfaceDiffEmpty: "#1e1e1e",
      surfaceSidebar: "#1e1e1e",
      surfaceSidebarHover: "#1e1e1e",
      foregroundMuted: "#bcbcbc",
      foregroundExtraMuted: "#8a8a8a",
      scrollbarHandle: "#8a8a8a",
      border: "#2e2e2e",
      borderAccent: "#2e2e2e",
      accent: "#4cadd6",
      accentBright: "#61b7db",
      accentForeground: "#000000",
      destructive: "#f65048",
});

const light = {
  surface0: "#e6e5e5",
  surface1: "#c2c2c2",
  surface2: "#c2c2c2",
  surface3: "#cacaca",
  surface4: "#cacaca",
  surfaceDiffEmpty: "#c2c2c2",
  surfaceSidebar: "#c2c2c2",
  surfaceSidebarHover: "#c2c2c2",
  foreground: "#1a1a1e",
  foregroundMuted: "#1a1a1e",
  foregroundExtraMuted: "#1a1a1e",
  scrollbarHandle: "#1a1a1e",
  border: "#cacaca",
  borderAccent: "#cacaca",
  accent: "#46a5ce",
  accentBright: "#3f94b9",
  accentForeground: "#ffffff",
  destructive: "#c32424",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "cyber-glow",
  name: "Cyber Glow",
  source: { repo: "thepharaohart/Obsidian-CyberGlow", author: "thepharaohart", rank: 51 },
  dark,
  light,
  terminalDark: {
    background: "#000000",
    foreground: "#fafafa",
    cursor: "#fafafa",
    red: "#f65048",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#4cadd6",
    magenta: "#4cadd6",
    cyan: "#2ead58",
    white: "#fafafa",
    brightRed: "#f65048",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#4cadd6",
    brightMagenta: "#f65048",
    brightCyan: "#2ead58",
    brightWhite: "#fafafa",
  },
  terminalLight: {
    background: "#e6e5e5",
    foreground: "#1a1a1e",
    cursor: "#1a1a1e",
    red: "#c32424",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#46a5ce",
    magenta: "#46a5ce",
    cyan: "#1f8040",
    white: "#1a1a1e",
    brightRed: "#c32424",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#46a5ce",
    brightMagenta: "#c32424",
    brightCyan: "#1f8040",
    brightWhite: "#1a1a1e",
  },
};
