import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Ebullientworks — ported from Obsidian theme `ebullient/obsidian-theme-ebullientworks` by ebullient.
// Rank #50 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#1e1e1e",
      surface1: "#2f2f2f",
      surface2: "#272727",
      surface3: "#1b1b1b",
      surface4: "#1b1b1b",
      surfaceDiffEmpty: "#2f2f2f",
      surfaceSidebar: "#2f2f2f",
      surfaceSidebarHover: "#272727",
      foregroundMuted: "#b8b8b8",
      foregroundExtraMuted: "#a0a0a0",
      scrollbarHandle: "#a0a0a0",
      border: "#1b1b1b",
      borderAccent: "#1b1b1b",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#fafafa",
      destructive: "#f65048",
});

const light = {
  surface0: "#f8f8f8",
  surface1: "#e3e3e3",
  surface2: "#f1f1f1",
  surface3: "#cdcdcd",
  surface4: "#cdcdcd",
  surfaceDiffEmpty: "#e3e3e3",
  surfaceSidebar: "#e3e3e3",
  surfaceSidebarHover: "#f1f1f1",
  foreground: "#484848",
  foregroundMuted: "#5d5d5d",
  foregroundExtraMuted: "#a0a0a0",
  scrollbarHandle: "#a0a0a0",
  border: "#cdcdcd",
  borderAccent: "#cdcdcd",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#fafafa",
  destructive: "#c32424",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "ebullientworks",
  name: "Ebullientworks",
  source: { repo: "ebullient/obsidian-theme-ebullientworks", author: "ebullient", rank: 50 },
  dark,
  light,
  terminalDark: {
    background: "#1e1e1e",
    foreground: "#cdcdcd",
    cursor: "#cdcdcd",
    red: "#f65048",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#2d8b62",
    magenta: "#2d8b62",
    cyan: "#2ead58",
    white: "#cdcdcd",
    brightRed: "#f65048",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#2d8b62",
    brightMagenta: "#f65048",
    brightCyan: "#2ead58",
    brightWhite: "#cdcdcd",
  },
  terminalLight: {
    background: "#f8f8f8",
    foreground: "#484848",
    cursor: "#484848",
    red: "#c32424",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#2d8b62",
    magenta: "#2d8b62",
    cyan: "#1f8040",
    white: "#484848",
    brightRed: "#c32424",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#2d8b62",
    brightMagenta: "#c32424",
    brightCyan: "#1f8040",
    brightWhite: "#484848",
  },
};
