import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Encore — ported from Obsidian theme `carbonateb/obsidian-encore-theme` by carbonateb.
// Rank #30 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#000000",
      surface1: "#080808",
      surface2: "#141419",
      surface3: "#1a1a20",
      surface4: "#1a1a20",
      surfaceDiffEmpty: "#080808",
      surfaceSidebar: "#080808",
      surfaceSidebarHover: "#141419",
      foregroundMuted: "#a2a5ba",
      foregroundExtraMuted: "#7e8094",
      scrollbarHandle: "#7e8094",
      border: "#1a1a20",
      borderAccent: "#1a1a20",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#000000",
      destructive: "#bf616a",
});

const light = {
  surface0: "#ffffff",
  surface1: "#fafafa",
  surface2: "#e4e4e7",
  surface3: "#d1d5db",
  surface4: "#d1d5db",
  surfaceDiffEmpty: "#fafafa",
  surfaceSidebar: "#fafafa",
  surfaceSidebarHover: "#e4e4e7",
  foreground: "#1f2937",
  foregroundMuted: "#4b5563",
  foregroundExtraMuted: "#5a5a5a",
  scrollbarHandle: "#5a5a5a",
  border: "#d1d5db",
  borderAccent: "#d1d5db",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#ffffff",
  destructive: "#df2a51",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "encore",
  name: "Encore",
  source: { repo: "carbonateb/obsidian-encore-theme", author: "carbonateb", rank: 30 },
  dark,
  light,
  terminalDark: {
    background: "#000000",
    foreground: "#dee3f1",
    cursor: "#dee3f1",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
    blue: "#81a1c1",
    magenta: "#2d8b62",
    cyan: "#88c0d0",
    white: "#dee3f1",
    brightRed: "#bf616a",
    brightGreen: "#a3be8c",
    brightYellow: "#ebcb8b",
    brightBlue: "#81a1c1",
    brightMagenta: "#bf616a",
    brightCyan: "#88c0d0",
    brightWhite: "#dee3f1",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#1f2937",
    cursor: "#1f2937",
    red: "#df2a51",
    green: "#2adfb2",
    yellow: "#abe667",
    blue: "#5c87ff",
    magenta: "#2d8b62",
    cyan: "#2abbdf",
    white: "#1f2937",
    brightRed: "#df2a51",
    brightGreen: "#2adfb2",
    brightYellow: "#abe667",
    brightBlue: "#5c87ff",
    brightMagenta: "#df2a51",
    brightCyan: "#2abbdf",
    brightWhite: "#1f2937",
  },
};
