import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Gastown — ported from Obsidian theme `dogwaddle/obsidian-gastown-theme.md` by dogwaddle.
// Rank #89 by community popularity. Original modes: light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#ffffff",
      surface1: "#eceff2",
      surface2: "#ffffff",
      surface3: "#dddddd",
      surface4: "#dddddd",
      surfaceDiffEmpty: "#eceff2",
      surfaceSidebar: "#eceff2",
      surfaceSidebarHover: "#ffffff",
      foregroundMuted: "#000000",
      foregroundExtraMuted: "#999999",
      scrollbarHandle: "#999999",
      border: "#dddddd",
      borderAccent: "#dddddd",
      accent: "#020f2b",
      accentBright: "#8273e6",
      accentForeground: "#f2f2f2",
      destructive: "#f65048",
});

const light = {
  surface0: "#ffffff",
  surface1: "#eceff2",
  surface2: "#ffffff",
  surface3: "#dddddd",
  surface4: "#dddddd",
  surfaceDiffEmpty: "#eceff2",
  surfaceSidebar: "#eceff2",
  surfaceSidebarHover: "#ffffff",
  foreground: "#000000",
  foregroundMuted: "#000000",
  foregroundExtraMuted: "#999999",
  scrollbarHandle: "#999999",
  border: "#dddddd",
  borderAccent: "#dddddd",
  accent: "#020f2b",
  accentBright: "#8273e6",
  accentForeground: "#f2f2f2",
  destructive: "#800000",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "gastown",
  name: "Gastown",
  source: { repo: "dogwaddle/obsidian-gastown-theme.md", author: "dogwaddle", rank: 89 },
  dark,
  light,
  terminalDark: {
    background: "#ffffff",
    foreground: "#000000",
    cursor: "#000000",
    red: "#f65048",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#020f2b",
    magenta: "#020f2b",
    cyan: "#2ead58",
    white: "#000000",
    brightRed: "#f65048",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#020f2b",
    brightMagenta: "#f65048",
    brightCyan: "#2ead58",
    brightWhite: "#000000",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#000000",
    cursor: "#000000",
    red: "#800000",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#020f2b",
    magenta: "#020f2b",
    cyan: "#1f8040",
    white: "#000000",
    brightRed: "#800000",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#020f2b",
    brightMagenta: "#800000",
    brightCyan: "#1f8040",
    brightWhite: "#000000",
  },
};
