import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// MagicUser — ported from Obsidian theme `drbap/magicuser-theme-for-obsidian` by Bernardo Pires.
// Rank #56 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#383800",
      surface1: "#383800",
      surface2: "#212121",
      surface3: "#5c5c2e",
      surface4: "#5c5c2e",
      surfaceDiffEmpty: "#383800",
      surfaceSidebar: "#383800",
      surfaceSidebarHover: "#212121",
      foregroundMuted: "#bcbcbc",
      foregroundExtraMuted: "#8a8a8a",
      scrollbarHandle: "#8a8a8a",
      border: "#5c5c2e",
      borderAccent: "#5c5c2e",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#ffffff",
      destructive: "#e12828",
});

const light = {
  surface0: "#ffffbf",
  surface1: "#ffffbf",
  surface2: "#e1e1e1",
  surface3: "#e0e0a8",
  surface4: "#e0e0a8",
  surfaceDiffEmpty: "#ffffbf",
  surfaceSidebar: "#ffffbf",
  surfaceSidebarHover: "#e1e1e1",
  foreground: "#1a1a1e",
  foregroundMuted: "#1a1a1e",
  foregroundExtraMuted: "#1a1a1e",
  scrollbarHandle: "#1a1a1e",
  border: "#e0e0a8",
  borderAccent: "#e0e0a8",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#ffffff",
  destructive: "#ff8282",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "magicuser",
  name: "MagicUser",
  source: { repo: "drbap/magicuser-theme-for-obsidian", author: "Bernardo Pires", rank: 56 },
  dark,
  light,
  terminalDark: {
    background: "#383800",
    foreground: "#fafafa",
    cursor: "#fafafa",
    red: "#e12828",
    green: "#48e148",
    yellow: "#e1e100",
    blue: "#0048e1",
    magenta: "#d300e1",
    cyan: "#00e1e1",
    white: "#fafafa",
    brightRed: "#e12828",
    brightGreen: "#48e148",
    brightYellow: "#e1e100",
    brightBlue: "#0048e1",
    brightMagenta: "#e14fbf",
    brightCyan: "#00e1e1",
    brightWhite: "#fafafa",
  },
  terminalLight: {
    background: "#ffffbf",
    foreground: "#1a1a1e",
    cursor: "#1a1a1e",
    red: "#ff8282",
    green: "#bfffbf",
    yellow: "#ffffa3",
    blue: "#a3c3ff",
    magenta: "#d3bfff",
    cyan: "#bff1ef",
    white: "#1a1a1e",
    brightRed: "#ff8282",
    brightGreen: "#bfffbf",
    brightYellow: "#ffffa3",
    brightBlue: "#a3c3ff",
    brightMagenta: "#ffcfcf",
    brightCyan: "#bff1ef",
    brightWhite: "#1a1a1e",
  },
};
