import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Notation — ported from Obsidian theme `deathau/Notation-for-Obsidian` by deathau.
// Rank #25 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#2f3437",
      surface1: "#363c3f",
      surface2: "#3d4448",
      surface3: "#ffffff",
      surface4: "#ffffff",
      surfaceDiffEmpty: "#363c3f",
      surfaceSidebar: "#363c3f",
      surfaceSidebarHover: "#3d4448",
      foregroundMuted: "#ffffff",
      foregroundExtraMuted: "#ffffff",
      scrollbarHandle: "#ffffff",
      border: "#ffffff",
      borderAccent: "#ffffff",
      accent: "#2eaadc",
      accentBright: "#2eaadc",
      accentForeground: "#ffffff",
      destructive: "#f65048",
});

const light = {
  surface0: "#ffffff",
  surface1: "#f4f5f6",
  surface2: "#f4f5f6",
  surface3: "#37352f",
  surface4: "#37352f",
  surfaceDiffEmpty: "#f4f5f6",
  surfaceSidebar: "#f4f5f6",
  surfaceSidebarHover: "#f4f5f6",
  foreground: "#37352f",
  foregroundMuted: "#37352f",
  foregroundExtraMuted: "#37352f",
  scrollbarHandle: "#37352f",
  border: "#37352f",
  borderAccent: "#37352f",
  accent: "#2eaadc",
  accentBright: "#2eaadc",
  accentForeground: "#37352f",
  destructive: "#c32424",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "notation",
  name: "Notation",
  source: { repo: "deathau/Notation-for-Obsidian", author: "deathau", rank: 25 },
  dark,
  light,
  terminalDark: {
    background: "#2f3437",
    foreground: "#ffffff",
    cursor: "#ffffff",
    red: "#f65048",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#2eaadc",
    magenta: "#2eaadc",
    cyan: "#2ead58",
    white: "#ffffff",
    brightRed: "#f65048",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#2eaadc",
    brightMagenta: "#f65048",
    brightCyan: "#2ead58",
    brightWhite: "#ffffff",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#37352f",
    cursor: "#37352f",
    red: "#c32424",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#2eaadc",
    magenta: "#2eaadc",
    cyan: "#1f8040",
    white: "#37352f",
    brightRed: "#c32424",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#2eaadc",
    brightMagenta: "#c32424",
    brightCyan: "#1f8040",
    brightWhite: "#37352f",
  },
};
