import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Obsidianotion — ported from Obsidian theme `diegoeis/obsidianotion` by Diego Eis.
// Rank #34 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#1f1f1f",
      surface1: "#191919",
      surface2: "#1f1f1f",
      surface3: "#2c2c2c",
      surface4: "#2c2c2c",
      surfaceDiffEmpty: "#191919",
      surfaceSidebar: "#191919",
      surfaceSidebarHover: "#1f1f1f",
      foregroundMuted: "#9b9a97",
      foregroundExtraMuted: "#6e6d6a",
      scrollbarHandle: "#6e6d6a",
      border: "#2c2c2c",
      borderAccent: "#2c2c2c",
      accent: "#4dabf7",
      accentBright: "#74c0fc",
      accentForeground: "#0b0d12",
      destructive: "#ff6b6b",
});

const light = {
  surface0: "#ffffff",
  surface1: "#f9f8f7",
  surface2: "#ffffff",
  surface3: "#e6e6e6",
  surface4: "#e6e6e6",
  surfaceDiffEmpty: "#f9f8f7",
  surfaceSidebar: "#f9f8f7",
  surfaceSidebarHover: "#ffffff",
  foreground: "#31302e",
  foregroundMuted: "#615d59",
  foregroundExtraMuted: "#a39e98",
  scrollbarHandle: "#a39e98",
  border: "#e6e6e6",
  borderAccent: "#e6e6e6",
  accent: "#0075de",
  accentBright: "#005bab",
  accentForeground: "#ffffff",
  destructive: "#eb5757",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "obsidianotion",
  name: "Obsidianotion",
  source: { repo: "diegoeis/obsidianotion", author: "Diego Eis", rank: 34 },
  dark,
  light,
  terminalDark: {
    background: "#1f1f1f",
    foreground: "#e6e6e4",
    cursor: "#e6e6e4",
    red: "#ff6b6b",
    green: "#51cf66",
    yellow: "#c38328",
    blue: "#4dabf7",
    magenta: "#4dabf7",
    cyan: "#51cf66",
    white: "#e6e6e4",
    brightRed: "#ff6b6b",
    brightGreen: "#51cf66",
    brightYellow: "#c38328",
    brightBlue: "#4dabf7",
    brightMagenta: "#ff6b6b",
    brightCyan: "#51cf66",
    brightWhite: "#e6e6e4",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#31302e",
    cursor: "#31302e",
    red: "#eb5757",
    green: "#1aae39",
    yellow: "#91601b",
    blue: "#0075de",
    magenta: "#0075de",
    cyan: "#1aae39",
    white: "#31302e",
    brightRed: "#eb5757",
    brightGreen: "#1aae39",
    brightYellow: "#91601b",
    brightBlue: "#0075de",
    brightMagenta: "#eb5757",
    brightCyan: "#1aae39",
    brightWhite: "#31302e",
  },
};
