import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Obsidian Nord — ported from Obsidian theme `insanum/obsidian_nord` by insanum.
// Rank #5 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#2e3440",
      surface1: "#3b4252",
      surface2: "#2e3440",
      surface3: "#434c5e",
      surface4: "#434c5e",
      surfaceDiffEmpty: "#3b4252",
      surfaceSidebar: "#3b4252",
      surfaceSidebarHover: "#2e3440",
      foregroundMuted: "#e5e9f0",
      foregroundExtraMuted: "#d8dee9",
      scrollbarHandle: "#d8dee9",
      border: "#434c5e",
      borderAccent: "#434c5e",
      accent: "#d08770",
      accentBright: "#81a1c1",
      accentForeground: "#101010",
      destructive: "#bf616a",
});

const light = {
  surface0: "#ffffff",
  surface1: "#eceff4",
  surface2: "#ffffff",
  surface3: "#e5e9f0",
  surface4: "#e5e9f0",
  surfaceDiffEmpty: "#eceff4",
  surfaceSidebar: "#eceff4",
  surfaceSidebarHover: "#ffffff",
  foreground: "#434c5e",
  foregroundMuted: "#3b4252",
  foregroundExtraMuted: "#2e3440",
  scrollbarHandle: "#2e3440",
  border: "#e5e9f0",
  borderAccent: "#e5e9f0",
  accent: "#d08770",
  accentBright: "#81a1c1",
  accentForeground: "#101010",
  destructive: "#bf616a",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "obsidian-nord",
  name: "Obsidian Nord",
  source: { repo: "insanum/obsidian_nord", author: "insanum", rank: 5 },
  dark,
  light,
  terminalDark: {
    background: "#2e3440",
    foreground: "#eceff4",
    cursor: "#eceff4",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
    blue: "#5e81ac",
    magenta: "#b48ead",
    cyan: "#88c0d0",
    white: "#eceff4",
    brightRed: "#bf616a",
    brightGreen: "#a3be8c",
    brightYellow: "#ebcb8b",
    brightBlue: "#5e81ac",
    brightMagenta: "#bf616a",
    brightCyan: "#88c0d0",
    brightWhite: "#eceff4",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#434c5e",
    cursor: "#434c5e",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
    blue: "#5e81ac",
    magenta: "#b48ead",
    cyan: "#88c0d0",
    white: "#434c5e",
    brightRed: "#bf616a",
    brightGreen: "#a3be8c",
    brightYellow: "#ebcb8b",
    brightBlue: "#5e81ac",
    brightMagenta: "#bf616a",
    brightCyan: "#88c0d0",
    brightWhite: "#434c5e",
  },
};
