import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Obuntu — ported from Obsidian theme `dmytrodubinin/Obuntu-theme-for-Obsidian` by dmytrodubinin.
// Rank #28 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#343434",
      surface1: "#2c2c2c",
      surface2: "#2c2c2c",
      surface3: "#303030",
      surface4: "#303030",
      surfaceDiffEmpty: "#2c2c2c",
      surfaceSidebar: "#2c2c2c",
      surfaceSidebarHover: "#2c2c2c",
      foregroundMuted: "#999999",
      foregroundExtraMuted: "#666666",
      scrollbarHandle: "#666666",
      border: "#303030",
      borderAccent: "#303030",
      accent: "#df4a16",
      accentBright: "#df7a16",
      accentForeground: "#dcddde",
      destructive: "#ff3333",
});

const light = {
  surface0: "#ffffff",
  surface1: "#dedede",
  surface2: "#dedede",
  surface3: "#f7f7f7",
  surface4: "#f7f7f7",
  surfaceDiffEmpty: "#dedede",
  surfaceSidebar: "#dedede",
  surfaceSidebarHover: "#dedede",
  foreground: "#03050b",
  foregroundMuted: "#555555",
  foregroundExtraMuted: "#03050b",
  scrollbarHandle: "#03050b",
  border: "#f7f7f7",
  borderAccent: "#f7f7f7",
  accent: "#df4a16",
  accentBright: "#df7a16",
  accentForeground: "#dcddde",
  destructive: "#ff3333",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "obuntu",
  name: "Obuntu",
  source: { repo: "dmytrodubinin/Obuntu-theme-for-Obsidian", author: "dmytrodubinin", rank: 28 },
  dark,
  light,
  terminalDark: {
    background: "#343434",
    foreground: "#dcddde",
    cursor: "#dcddde",
    red: "#ff3333",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#df4a16",
    magenta: "#df4a16",
    cyan: "#2ead58",
    white: "#dcddde",
    brightRed: "#ff3333",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#df4a16",
    brightMagenta: "#ff3333",
    brightCyan: "#2ead58",
    brightWhite: "#dcddde",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#03050b",
    cursor: "#03050b",
    red: "#ff3333",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#df4a16",
    magenta: "#df4a16",
    cyan: "#1f8040",
    white: "#03050b",
    brightRed: "#ff3333",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#df4a16",
    brightMagenta: "#ff3333",
    brightCyan: "#1f8040",
    brightWhite: "#03050b",
  },
};
