import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Things — ported from Obsidian theme `colineckert/obsidian-things` by colineckert.
// Rank #2 by community popularity. Original modes: light, dark.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#000000",
      surface1: "#282c34",
      surface2: "#ebedf0",
      surface3: "#ebedf0",
      surface4: "#ebedf0",
      surfaceDiffEmpty: "#282c34",
      surfaceSidebar: "#282c34",
      surfaceSidebarHover: "#ebedf0",
      foregroundMuted: "#bec6cf",
      foregroundExtraMuted: "#5d6d7e",
      scrollbarHandle: "#5d6d7e",
      border: "#ebedf0",
      borderAccent: "#ebedf0",
      accent: "#4c8ce6",
      accentBright: "#afcbf4",
      accentForeground: "#000000",
      destructive: "#fb464c",
});

const light = {
  surface0: "#ffffff",
  surface1: "#f6f7f8",
  surface2: "#fcfcfc",
  surface3: "#ebedf0",
  surface4: "#ebedf0",
  surfaceDiffEmpty: "#f6f7f8",
  surfaceSidebar: "#f6f7f8",
  surfaceSidebarHover: "#fcfcfc",
  foreground: "#222222",
  foregroundMuted: "#555e68",
  foregroundExtraMuted: "#a2aab3",
  scrollbarHandle: "#a2aab3",
  border: "#ebedf0",
  borderAccent: "#ebedf0",
  accent: "#4c8ce6",
  accentBright: "#2070df",
  accentForeground: "#ffffff",
  destructive: "#e4374b",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "things",
  name: "Things",
  source: { repo: "colineckert/obsidian-things", author: "colineckert", rank: 2 },
  dark,
  light,
  terminalDark: {
    background: "#000000",
    foreground: "#dadada",
    cursor: "#dadada",
    red: "#fb464c",
    green: "#44cf6e",
    yellow: "#e0de71",
    blue: "#027aff",
    magenta: "#a882ff",
    cyan: "#53dfdd",
    white: "#dadada",
    brightRed: "#fb464c",
    brightGreen: "#44cf6e",
    brightYellow: "#e0de71",
    brightBlue: "#027aff",
    brightMagenta: "#fa99cd",
    brightCyan: "#53dfdd",
    brightWhite: "#dadada",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#222222",
    cursor: "#222222",
    red: "#e4374b",
    green: "#0cb54f",
    yellow: "#bd8e37",
    blue: "#086ddd",
    magenta: "#876be0",
    cyan: "#2db7b5",
    white: "#222222",
    brightRed: "#e4374b",
    brightGreen: "#0cb54f",
    brightYellow: "#bd8e37",
    brightBlue: "#086ddd",
    brightMagenta: "#c32b74",
    brightCyan: "#2db7b5",
    brightWhite: "#222222",
  },
};
