import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Typora-Vue — ported from Obsidian theme `zekunc/Obsidian-Typora-Vue-Theme` by zekunc.
// Rank #41 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#ffffff",
      surface1: "#ffffff",
      surface2: "#ffffff",
      surface3: "#ffffff",
      surface4: "#ffffff",
      surfaceDiffEmpty: "#ffffff",
      surfaceSidebar: "#ffffff",
      surfaceSidebarHover: "#ffffff",
      foregroundMuted: "#b2b2b2",
      foregroundExtraMuted: "#838383",
      scrollbarHandle: "#838383",
      border: "#ffffff",
      borderAccent: "#ffffff",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#ffffff",
      destructive: "#f65048",
});

const light = {
  surface0: "#ffffff",
  surface1: "#ffffff",
  surface2: "#ffffff",
  surface3: "#e0e0e0",
  surface4: "#e0e0e0",
  surfaceDiffEmpty: "#ffffff",
  surfaceSidebar: "#ffffff",
  surfaceSidebarHover: "#ffffff",
  foreground: "#34495e",
  foregroundMuted: "#34495e",
  foregroundExtraMuted: "#34495e",
  scrollbarHandle: "#34495e",
  border: "#e0e0e0",
  borderAccent: "#e0e0e0",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#ffffff",
  destructive: "#c32424",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "typora-vue",
  name: "Typora-Vue",
  source: { repo: "zekunc/Obsidian-Typora-Vue-Theme", author: "zekunc", rank: 41 },
  dark,
  light,
  terminalDark: {
    background: "#ffffff",
    foreground: "#eeeeee",
    cursor: "#eeeeee",
    red: "#f65048",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#2d8b62",
    magenta: "#2d8b62",
    cyan: "#2ead58",
    white: "#eeeeee",
    brightRed: "#f65048",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#2d8b62",
    brightMagenta: "#f65048",
    brightCyan: "#2ead58",
    brightWhite: "#eeeeee",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#34495e",
    cursor: "#34495e",
    red: "#c32424",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#2d8b62",
    magenta: "#2d8b62",
    cyan: "#1f8040",
    white: "#34495e",
    brightRed: "#c32424",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#2d8b62",
    brightMagenta: "#c32424",
    brightCyan: "#1f8040",
    brightWhite: "#34495e",
  },
};
