import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Typomagical — ported from Obsidian theme `hungsu/typomagical-obsidian` by hungsu.
// Rank #26 by community popularity. Original modes: light, dark.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#000000",
      surface1: "#000000",
      surface2: "#000000",
      surface3: "#e8aa99",
      surface4: "#e8aa99",
      surfaceDiffEmpty: "#000000",
      surfaceSidebar: "#000000",
      surfaceSidebarHover: "#000000",
      foregroundMuted: "#e5e9f0",
      foregroundExtraMuted: "#cccccc",
      scrollbarHandle: "#cccccc",
      border: "#e8aa99",
      borderAccent: "#e8aa99",
      accent: "#89b4fa",
      accentBright: "#74c7ec",
      accentForeground: "#fbf1c7",
      destructive: "#800000",
});

const light = {
  surface0: "#ffffff",
  surface1: "#ffffff",
  surface2: "#ffffff",
  surface3: "#beb28e",
  surface4: "#beb28e",
  surfaceDiffEmpty: "#ffffff",
  surfaceSidebar: "#ffffff",
  surfaceSidebarHover: "#ffffff",
  foreground: "#3a527e",
  foregroundMuted: "#67799e",
  foregroundExtraMuted: "#7383a5",
  scrollbarHandle: "#7383a5",
  border: "#beb28e",
  borderAccent: "#beb28e",
  accent: "#df8e1d",
  accentBright: "#fe640b",
  accentForeground: "#f2f2f2",
  destructive: "#800000",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "typomagical",
  name: "Typomagical",
  source: { repo: "hungsu/typomagical-obsidian", author: "hungsu", rank: 26 },
  dark,
  light,
  terminalDark: {
    background: "#000000",
    foreground: "#eceff4",
    cursor: "#eceff4",
    red: "#800000",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#89b4fa",
    magenta: "#89b4fa",
    cyan: "#2ead58",
    white: "#eceff4",
    brightRed: "#800000",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#89b4fa",
    brightMagenta: "#800000",
    brightCyan: "#2ead58",
    brightWhite: "#eceff4",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#3a527e",
    cursor: "#3a527e",
    red: "#800000",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#df8e1d",
    magenta: "#df8e1d",
    cyan: "#1f8040",
    white: "#3a527e",
    brightRed: "#800000",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#df8e1d",
    brightMagenta: "#800000",
    brightCyan: "#1f8040",
    brightWhite: "#3a527e",
  },
};
