import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Vauxhall — ported from Obsidian theme `cyanvoxel/vauxhall-obsidian` by cyanvoxel.
// Rank #42 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#1a1a1e",
      surface1: "#28282c",
      surface2: "#3a3a3e",
      surface3: "#434346",
      surface4: "#434346",
      surfaceDiffEmpty: "#28282c",
      surfaceSidebar: "#28282c",
      surfaceSidebarHover: "#3a3a3e",
      foregroundMuted: "#bcbcbc",
      foregroundExtraMuted: "#8a8a8a",
      scrollbarHandle: "#8a8a8a",
      border: "#434346",
      borderAccent: "#434346",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#ffffff",
      destructive: "#e3365e",
});

const light = {
  surface0: "#ffffff",
  surface1: "#f5f5f5",
  surface2: "#e8e8e8",
  surface3: "#e0e0e0",
  surface4: "#e0e0e0",
  surfaceDiffEmpty: "#f5f5f5",
  surfaceSidebar: "#f5f5f5",
  surfaceSidebarHover: "#e8e8e8",
  foreground: "#1a1a1e",
  foregroundMuted: "#1a1a1e",
  foregroundExtraMuted: "#1a1a1e",
  scrollbarHandle: "#1a1a1e",
  border: "#e0e0e0",
  borderAccent: "#e0e0e0",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#ffffff",
  destructive: "#e3365e",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "vauxhall",
  name: "Vauxhall",
  source: { repo: "cyanvoxel/vauxhall-obsidian", author: "cyanvoxel", rank: 42 },
  dark,
  light,
  terminalDark: {
    background: "#1a1a1e",
    foreground: "#fafafa",
    cursor: "#fafafa",
    red: "#e3365e",
    green: "#52eea3",
    yellow: "#ffd85e",
    blue: "#437cf3",
    magenta: "#9446f8",
    cyan: "#43cfea",
    white: "#fafafa",
    brightRed: "#e3365e",
    brightGreen: "#52eea3",
    brightYellow: "#ffd85e",
    brightBlue: "#437cf3",
    brightMagenta: "#e54f9b",
    brightCyan: "#43cfea",
    brightWhite: "#fafafa",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#1a1a1e",
    cursor: "#1a1a1e",
    red: "#e3365e",
    green: "#47cc91",
    yellow: "#ffd85e",
    blue: "#437cf3",
    magenta: "#9446f8",
    cyan: "#3bb2ce",
    white: "#1a1a1e",
    brightRed: "#e3365e",
    brightGreen: "#47cc91",
    brightYellow: "#ffd85e",
    brightBlue: "#437cf3",
    brightMagenta: "#e54f9b",
    brightCyan: "#3bb2ce",
    brightWhite: "#1a1a1e",
  },
};
