import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Velocity — ported from Obsidian theme `gonzalo-d-sales/obsidian-velocity` by gonzalo-d-sales.
// Rank #44 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#1a1a1e",
      surface1: "#28282c",
      surface2: "#3a3a3e",
      surface3: "#434346",
      surface4: "#434346",
      surfaceDiffEmpty: "#28282c",
      surfaceSidebar: "#28282c",
      surfaceSidebarHover: "#3a3a3e",
      foregroundMuted: "#bcbcbc",
      foregroundExtraMuted: "#8a8a8a",
      scrollbarHandle: "#8a8a8a",
      border: "#434346",
      borderAccent: "#434346",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#ffffff",
      destructive: "#ff5853",
});

const light = {
  surface0: "#ffffff",
  surface1: "#f5f5f5",
  surface2: "#e8e8e8",
  surface3: "#e0e0e0",
  surface4: "#e0e0e0",
  surfaceDiffEmpty: "#f5f5f5",
  surfaceSidebar: "#f5f5f5",
  surfaceSidebarHover: "#e8e8e8",
  foreground: "#1a1a1e",
  foregroundMuted: "#1a1a1e",
  foregroundExtraMuted: "#1a1a1e",
  scrollbarHandle: "#1a1a1e",
  border: "#e0e0e0",
  borderAccent: "#e0e0e0",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#ffffff",
  destructive: "#f4291b",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "velocity",
  name: "Velocity",
  source: { repo: "gonzalo-d-sales/obsidian-velocity", author: "gonzalo-d-sales", rank: 44 },
  dark,
  light,
  terminalDark: {
    background: "#1a1a1e",
    foreground: "#fafafa",
    cursor: "#fafafa",
    red: "#ff5853",
    green: "#77cb4d",
    yellow: "#d0cb69",
    blue: "#009bff",
    magenta: "#cb74e4",
    cyan: "#63d5cd",
    white: "#fafafa",
    brightRed: "#ff5853",
    brightGreen: "#77cb4d",
    brightYellow: "#d0cb69",
    brightBlue: "#009bff",
    brightMagenta: "#ff98b9",
    brightCyan: "#63d5cd",
    brightWhite: "#fafafa",
  },
  terminalLight: {
    background: "#ffffff",
    foreground: "#1a1a1e",
    cursor: "#1a1a1e",
    red: "#f4291b",
    green: "#36b359",
    yellow: "#f2a100",
    blue: "#0091f0",
    magenta: "#9755e7",
    cyan: "#04a8b2",
    white: "#1a1a1e",
    brightRed: "#f4291b",
    brightGreen: "#36b359",
    brightYellow: "#f2a100",
    brightBlue: "#0091f0",
    brightMagenta: "#f046ab",
    brightCyan: "#04a8b2",
    brightWhite: "#1a1a1e",
  },
};
