import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Vicious — ported from Obsidian theme `zaheralmajed/vicious-theme-obsidian` by zaheralmajed.
// Rank #57 by community popularity. Original modes: light, dark.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#08090e",
      surface1: "#08090e",
      surface2: "#08090e",
      surface3: "#292a2f",
      surface4: "#292a2f",
      surfaceDiffEmpty: "#08090e",
      surfaceSidebar: "#08090e",
      surfaceSidebarHover: "#08090e",
      foregroundMuted: "#818184",
      foregroundExtraMuted: "#68696c",
      scrollbarHandle: "#68696c",
      border: "#292a2f",
      borderAccent: "#292a2f",
      accent: "#2d8b62",
      accentBright: "#469975",
      accentForeground: "#08090e",
      destructive: "#f18196",
});

const light = {
  surface0: "#fbfcfc",
  surface1: "#fbfcfc",
  surface2: "#fbfcfc",
  surface3: "#818184",
  surface4: "#818184",
  surfaceDiffEmpty: "#fbfcfc",
  surfaceSidebar: "#fbfcfc",
  surfaceSidebarHover: "#fbfcfc",
  foreground: "#08090e",
  foregroundMuted: "#818184",
  foregroundExtraMuted: "#818184",
  scrollbarHandle: "#818184",
  border: "#818184",
  borderAccent: "#818184",
  accent: "#2d8b62",
  accentBright: "#287d58",
  accentForeground: "#08090e",
  destructive: "#f18196",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "vicious",
  name: "Vicious",
  source: { repo: "zaheralmajed/vicious-theme-obsidian", author: "zaheralmajed", rank: 57 },
  dark,
  light,
  terminalDark: {
    background: "#08090e",
    foreground: "#fbfcfc",
    cursor: "#fbfcfc",
    red: "#f18196",
    green: "#81f1a4",
    yellow: "#ebcb8b",
    blue: "#bcf181",
    magenta: "#ab8beb",
    cyan: "#8be3eb",
    white: "#fbfcfc",
    brightRed: "#f18196",
    brightGreen: "#81f1a4",
    brightYellow: "#ebcb8b",
    brightBlue: "#bcf181",
    brightMagenta: "#ee81f1",
    brightCyan: "#8be3eb",
    brightWhite: "#fbfcfc",
  },
  terminalLight: {
    background: "#fbfcfc",
    foreground: "#08090e",
    cursor: "#08090e",
    red: "#f18196",
    green: "#81f1a4",
    yellow: "#ebcb8b",
    blue: "#bcf181",
    magenta: "#ab8beb",
    cyan: "#8be3eb",
    white: "#08090e",
    brightRed: "#f18196",
    brightGreen: "#81f1a4",
    brightYellow: "#ebcb8b",
    brightBlue: "#bcf181",
    brightMagenta: "#ee81f1",
    brightCyan: "#8be3eb",
    brightWhite: "#08090e",
  },
};
