import { buildDarkSemanticColors } from "./_builder.js";
import type { PaseoThemeDefinition } from "./_types.js";

// Yin and Yang — ported from Obsidian theme `chetachiezikeuzor/Yin-and-Yang-Theme` by chetachiezikeuzor.
// Rank #35 by community popularity. Original modes: dark, light.
// Source palettes extracted from the upstream theme.css (see SOURCES.md).

const dark = buildDarkSemanticColors({
      surface0: "#0a0d10",
      surface1: "#0e1316",
      surface2: "#141a1f",
      surface3: "#ecedf1",
      surface4: "#ecedf1",
      surfaceDiffEmpty: "#0e1316",
      surfaceSidebar: "#0e1316",
      surfaceSidebarHover: "#141a1f",
      foregroundMuted: "#8ca4b5",
      foregroundExtraMuted: "#4c6170",
      scrollbarHandle: "#4c6170",
      border: "#ecedf1",
      borderAccent: "#ecedf1",
      accent: "#ffccf1",
      accentBright: "#ffb2e9",
      accentForeground: "#ffffff",
      destructive: "#f65048",
});

const light = {
  surface0: "#fcfdfd",
  surface1: "#ecf0f3",
  surface2: "#eff3f5",
  surface3: "#e0e6eb",
  surface4: "#e0e6eb",
  surfaceDiffEmpty: "#ecf0f3",
  surfaceSidebar: "#ecf0f3",
  surfaceSidebarHover: "#eff3f5",
  foreground: "#1d282f",
  foregroundMuted: "#5a7487",
  foregroundExtraMuted: "#afbfcb",
  scrollbarHandle: "#afbfcb",
  border: "#e0e6eb",
  borderAccent: "#e0e6eb",
  accent: "#d9adff",
  accentBright: "#e0bdff",
  accentForeground: "#ffffff",
  destructive: "#c32424",
  destructiveForeground: "#ffffff",
};

export const theme: PaseoThemeDefinition = {
  slug: "yin-and-yang",
  name: "Yin and Yang",
  source: { repo: "chetachiezikeuzor/Yin-and-Yang-Theme", author: "chetachiezikeuzor", rank: 35 },
  dark,
  light,
  terminalDark: {
    background: "#0a0d10",
    foreground: "#f2f8fd",
    cursor: "#f2f8fd",
    red: "#f65048",
    green: "#2ead58",
    yellow: "#c38328",
    blue: "#ffccf1",
    magenta: "#ffccf1",
    cyan: "#2ead58",
    white: "#f2f8fd",
    brightRed: "#f65048",
    brightGreen: "#2ead58",
    brightYellow: "#c38328",
    brightBlue: "#ffccf1",
    brightMagenta: "#f65048",
    brightCyan: "#2ead58",
    brightWhite: "#f2f8fd",
  },
  terminalLight: {
    background: "#fcfdfd",
    foreground: "#1d282f",
    cursor: "#1d282f",
    red: "#c32424",
    green: "#1f8040",
    yellow: "#91601b",
    blue: "#d9adff",
    magenta: "#d9adff",
    cyan: "#1f8040",
    white: "#1d282f",
    brightRed: "#c32424",
    brightGreen: "#1f8040",
    brightYellow: "#91601b",
    brightBlue: "#d9adff",
    brightMagenta: "#c32424",
    brightCyan: "#1f8040",
    brightWhite: "#1d282f",
  },
};
